// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GerenciamentoProcessos.Models;

public partial class DistribuicaoProcesso
{
    public Guid Id { get; set; }

    public Guid? ProcessoId { get; set; }

    public Guid? ProcuradorOrigemId { get; set; }

    public Guid? ProcuradorDestinoId { get; set; }

    public DateTime? DataTransferencia { get; set; }

    public virtual Processo Processo { get; set; }

    public virtual Procurador ProcuradorDestino { get; set; }

    public virtual Procurador ProcuradorOrigem { get; set; }
}