// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GerenciamentoProcessos.Models;

public partial class Prazo
{
    public Guid Id { get; set; }

    public Guid? ProcessoId { get; set; }

    public string Tipo { get; set; }

    public DateOnly? DataVencimento { get; set; }

    public int Status { get; set; }

    public virtual Processo Processo { get; set; }
}