// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GerenciamentoProcessos.Models;

public partial class Processo
{
    public Guid Id { get; set; }

    public string Numero { get; set; }

    public string OrgaoResponsavel { get; set; }

    public string Assunto { get; set; }

    public string Status { get; set; }

    public Guid? ProcuradorId { get; set; }

    public Guid? ClienteId { get; set; }

    public virtual Cliente Cliente { get; set; }

    public virtual ICollection<DistribuicaoProcesso> DistribuicaoProcessos { get; set; } = new List<DistribuicaoProcesso>();

    public virtual ICollection<Documento> Documentos { get; set; } = new List<Documento>();

    public virtual ICollection<Prazo> Prazos { get; set; } = new List<Prazo>();

    public virtual Procurador Procurador { get; set; }
}